CREATE TABLE DKXCONGTAC (
    DKX_ID INT NOT NULL PRIMARY KEY IDENTITY,
    DKX_Nguoichuanbi NVARCHAR(30) NOT NULL,
    DKX_Ngaybatdau DATE NOT NULL,
    DKX_Ngayketthuc DATE NOT NULL,
	DKX_Noidi NVARCHAR(50) NOT NULL,
	DKX_Noiden NVARCHAR(50) NOT NULL,
	DKX_Thanhphan NVARCHAR(50) NOT NULL,
	DKX_Sokm NVARCHAR(3) NOT NULL,
	DKX_Soghedukien NVARCHAR(3) NOT NULL,
	DKX_Noidung NVARCHAR(100) NOT NULL,
	DKX_Donvichutri NVARCHAR(50) NOT NULL,
	DKX_Ghichu NVARCHAR(50) NOT NULL
)
